# Default values for todo-api.
# This is a YAML-formatted file.

# Number of pod replicas to run
replicaCount: 1

# Container image configuration
image:
  repository: ghcr.io/aleksandar758/dotnet-todo
  # tag will be set by the deployment
  pullPolicy: IfNotPresent

# Provide a name override for resources
nameOverride: ""
fullnameOverride: ""

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Resource limits and requests
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Pod scheduling configuration
nodeSelector: {}
tolerations: []
affinity: {}

# Environment variables
env: []