---
name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t dotnet-todo:latest .

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          cpus: 2
          memory: 4096
          kubernetes-version: v1.27.3

      - name: Load Docker image into Minikube
        run: |
          minikube image load dotnet-todo:latest

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy Helm chart
        run: |
          helm upgrade --install todo ./dotnet-todo-chart \
            --set image.repository=dotnet-todo \
            --set image.tag=latest

      - name: Wait for deployment to stabilize
        run: kubectl rollout status deployment/todo

      - name: Test app endpoint
        run: |
          POD_NAME=$(kubectl get pods -l app.kubernetes.io/name=todo -o \
            jsonpath="{.items[0].metadata.name}")
          kubectl exec $POD_NAME -- curl -s http://localhost:5000/api/todo
