---
name: Build Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t dotnet-todo:latest ./src

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create version tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "aleksandar.milevski4@outlook.com"
          git config --global user.name "GitHub Actions"
          git tag v${{ steps.date.outputs.date }}
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{
            github.repository }}" v${{ steps.date.outputs.date }}
