name: Build and Tag Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for advanced build features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry (optional if pushing image)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Get current date for versioning
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t dotnet-todo:latest ./src
          docker tag dotnet-todo:latest ghcr.io/${{ github.repository_owner }}/dotnet-todo:${{ steps.date.outputs.date }}

      # Step 6: Push image to GitHub Container Registry (optional)
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/dotnet-todo:${{ steps.date.outputs.date }}

      # Step 7: Create Git tag for the build
      - name: Create Git version tag
        run: |
          git config --global user.email "aleksandar.milevski4@outlook.com"
          git config --global user.name "GitHub Actions"
          git tag v${{ steps.date.outputs.date }}
          git push origin v${{ steps.date.outputs.date }}
