name: Kubernetes Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: dotnet-todo:latest
        outputs: type=docker,dest=/tmp/dotnet-todo.tar
    
    - name: Set up Minikube
      uses: medyagh/setup-minikube@master
    
    - name: Load Docker image into Minikube
      run: |
        minikube image load /tmp/dotnet-todo.tar
        minikube image ls | grep dotnet-todo
    
    - name: Deploy with Helm
      run: |
        helm upgrade --install todo-api ./helm/todo-api
        kubectl rollout status deployment/todo-api
    
    - name: Test deployment
      run: |
        kubectl get pods -o wide
        kubectl get services
        minikube service list
